backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "/media"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
